name: Smoke Tests

on:
  workflow_call:

jobs:			
  smoke-tests:
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
          role-session-name: cipush
          aws-region: eu-central-1

      - id: ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Run smoke tests
        shell: bash
        run: |
          set -eaxo pipefail
          if [ ! -d smoke-tests ]; then
              echo "::warning No repo specific smoke tests defined"
              exit 0
          fi
          for d in smoke-tests/*/
          do
              echo Attempting to test $d
              if [ -d $d ] && [ -e $d/test.sh ]; then
                  cd $d
                  ./test.sh {{`${{ steps.ecr.outputs.registry }}`}}/{{ .Name }}:sha-{{`${{ github.sha }}`}}
                  cd -
              fi
          done
